version: '3.8'

services:
  # Sever NGINX
  nginx:
    container_name: WWW
    image: nginx:1.21.6-alpine
    ports:
      - 5464:80
    volumes:
      - ./nginx/:/etc/nginx/conf.d
      - ./laravel:/var/www/laravel/
    links:
      - phpfpm
    depends_on:
      - phpfpm
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - attendance
  
  # PHP
  phpfpm:
    container_name: PHP
    build:
      context: .
      dockerfile: ./php-fpm/Dockerfile
    volumes:
        - ./laravel:/var/www/laravel/
        - ./php-fpm/php.ini:/usr/local/etc/php/php.ini
    links: 
        - db
    depends_on:
        - db
    environment:
        - DB_HOST=db
        - DB_DATABASE=attendance_main
        - DB_USERNAME=root
        - DB_PASSWORD=root
    working_dir: "/var/www/laravel/"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - attendance
  
  # Database Mysql
  db:
    image: mysql:8.0.28
    container_name: MYSQL
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: attendance_main
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Ho_Chi_Minh'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db/sql:/docker-entrypoint-initdb.d
    ports:
      - 5465:3306
    networks:
      - attendance

  # PhpMyAdmin
  phpmyadmin:
    container_name: phpmyadmin
    restart: always
    depends_on:
      - db
    image: phpmyadmin:5.1.3
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=db
      - PMA_USER=root
      - PMA_PASSWORD=root
    ports:
      - 5466:80
    networks:
      - attendance
networks:
  attendance: